// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prysm-diagram/CommandCenter.tsx": () => import("../components/mockups/prysm-diagram/CommandCenter.tsx"),
  "./components/mockups/prysm-diagram/FlowDiagram.tsx": () => import("../components/mockups/prysm-diagram/FlowDiagram.tsx"),
  "./components/mockups/prysm-diagram/MinimalGrid.tsx": () => import("../components/mockups/prysm-diagram/MinimalGrid.tsx")
};
